# shellcheck disable=SC2034
{
  declare BL64_CRYP_MOD_VERSION='2.6.0'
  declare BL64_CRYP_MOD_INFO='Cryptographic Tools Interface'
  declare BL64_CRYP_MOD_SETUP='0'

  declare BL64_CRYP_CMD_GPG="$BL64_VAR_UNAVAILABLE"
  declare BL64_CRYP_CMD_OPENSSL="$BL64_VAR_UNAVAILABLE"
  declare BL64_CRYP_CMD_MD5SUM="$BL64_VAR_UNAVAILABLE"
  declare BL64_CRYP_CMD_SHA256SUM="$BL64_VAR_UNAVAILABLE"
}
